services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend/.env
    environment:
      - APP_ENVIRONMENT=LOCAL
    volumes:
      - ./backend:/app
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "user"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=khouryclassroomdb
      - POSTGRES_PASSWORD=pwd
    ports:
      - "5434:5432"
    volumes:
      - ./backend/database/migrations:/docker-entrypoint-initdb.d/
volumes:
  db:
    driver: local
